version: "3.3"

services:
  nginx:
    build: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - media_volume:/media
    depends_on:
      - admin
    networks:
      - gift_network

  admin:
    build:
      dockerfile: django_gift/Dockerfile
      context: .
    command: ../scripts/web/startup.sh -mm -m -l
    volumes:
      - ./django_gift:/code
      - media_volume:/media
    env_file:
      - django_gift/.env
    depends_on:
      - main_db
      - redis
    networks:
      - gift_network

  bot:
    build:
      dockerfile: bot/Dockerfile
      context: .
    command: python main.py
    volumes:
      - ./bot:/code
      - media_volume:/media
    env_file:
      - bot/.env
    depends_on:
      - main_db
      - redis
      - admin
    networks:
      - gift_network

  main_db:
    image: postgres:13.2
    env_file:
      - .env.db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "gift_user", "-d", "postgres"]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - gift_network

  redis:
    image: redis:6.2.4
    networks:
      - gift_network

volumes:
    media_volume:

networks:
  gift_network:
    external:
      name: gift_network